spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          flushMode: COMMIT
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: Neoa2912
